### ISSUE TITLE
configuration.module.rules[2].loader should be a non-empty string.

### ISSUE THREAD

**Issue by jfg** [inbucket/inbucket#244]
Hello !

I have this issue when i run my npm build !

```
root@..:/var/local/inbucket/ui# npm run build

> inbucket-ui@3.0.0 build
> webpack --mode production

[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.module.rules[2] should be one of these:
   ["..." | object { assert?, compiler?, dependency?, descriptionData?, enforce?, exclude?, generator?, include?, issuer?, issuerLayer?, layer?, loader?, mimetype?, oneOf?, options?, parser?, realResource?, resolve?, resource?, resourceFragment?, resourceQuery?, rules?, scheme?, sideEffects?, test?, type?, use? }, ...]
   -> A rule.
   Details:
    * configuration.module.rules[2].loader should be a non-empty string.
      -> A loader request.
npm ERR! code 2
npm ERR! path /var/local/inbucket/ui
npm ERR! command failed
npm ERR! command sh -c webpack --mode production

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-11T11_57_41_605Z-debug.log
```

And this is the log:

```
root@..:/var/local/inbucket/ui# cat /root/.npm/_logs/2021-12-11T11_57_41_605Z-debug.log
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
1 info using npm@7.5.2
2 info using node@v12.22.5
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 3ms
5 timing config:load:builtin Completed in 3ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/var/local/inbucket/ui/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/root/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 11ms
19 verbose npm-session b8ccadc411fc2e7f
20 timing npm:load Completed in 27ms
21 timing command:run-script Completed in 1260ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:314:20)
22 verbose stack     at maybeClose (internal/child_process.js:1022:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
23 verbose pkgid inbucket-ui@3.0.0
24 verbose cwd /var/local/inbucket/ui
25 verbose Linux 5.10.0-9-cloud-amd64
26 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
27 verbose node v12.22.5
28 verbose npm  v7.5.2
29 error code 2
30 error path /var/local/inbucket/ui
31 error command failed
32 error command sh -c webpack --mode production
33 verbose exit 2
```

Thanks for you help.

**Comment by jhillyerd** [comment]
Thanks for the report.  I'm not very experienced with webpack, but I suspect this line may be the cause:

https://github.com/inbucket/inbucket/blob/master/ui/webpack.config.js#L39

Perhaps webpack has changed the syntax for chaining loaders.

**Comment by jhillyerd** [comment]
As a quick test, I ran:

```sh
rm -rf dist/ elm-stuff/ node_modules/
rm -rf ~/.npm/
npm i
npm run build
```

and did not see the is problem, so your environment seems to be picking up a different release of webpack than what we have listed in the package.json.

**Comment by jfg** [comment]
Hello, 
thanks for your return.
Yes, i ran your commands and now that's OK.

**Comment by jfg** [comment]
Hello, 
thanks for your return.
Yes, i ran your commands and now that's OK.
